// Objektorienteeritud programmeerimine 2023/24 kevad                                                                                                                                                                                      
                                                                                                                                                                                                                                           
// Projekt: Mäng "Timukas", inglise keeles "Hangman", kus mängija arvab tähthaaval ära failist ettantud sõna.                                                                                                                              
                                                                                                                                                                                                                                           
// Autor: Mona Eliise Mumm (rühm 16)                                                                                                                                                                                                       
                                                                                                                                                                                                                                           
import java.io.File;                                                                                                                                                                                                                       
import java.util.ArrayList;                                                                                                                                                                                                                
import java.util.List;                                                                                                                                                                                                                     
import java.util.Random;                                                                                                                                                                                                                   
import java.util.Scanner;                                                                                                                                                                                                                  
                                                                                                                                                                                                                                           
public class Timukas {                                                                                                                                                                                                                     
                                                                                                                                                                                                                                           
    public static void main(String[] args) throws Exception {                                                                                                                                                                              
                                                                                                                                                                                                                                           
        Programm("OOP tekstifail.txt");                                                                                                                                                                                                    
                                                                                                                                                                                                                                           
    }                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                           
    // Failist lugemine ja programmi üleüldine töö toimub siin meetodis:                                                                                                                                                                   
    // 1. Võtame ette faili, kust sõnu hakata sisse lugema.                                                                                                                                                                                
    // 2. Sõnad failist lähevad Listi sõnad.                                                                                                                                                                                               
    // 3. Random klassi abil leiame sellest listist suvalise sõna, mida käsitlema hakata.                                                                                                                                                  
    // 4. Mängija pakutavad tähed/sõnad lähevad listi mängijaarvab.                                                                                                                                                                        
    // 5. Kasutame meetodit SõnaSeis, et hoida silm peal sõna äraarvamise hetkeseisu.                                                                                                                                                      
    // 6. Kasutame meetodit prindiMees, et valeVastuseLoenduri abil printida kriipsujukut.                                                                                                                                                 
    public static void Programm(String failinimi) throws Exception {                                                                                                                                                                       
        Scanner klaviatuuriInput = new Scanner(System.in);                                                                                                                                                                                 
        List<String> sõnad = new ArrayList<>();                                                                                                                                                                                            
        File fail = new File(failinimi);                                                                                                                                                                                                   
                                                                                                                                                                                                                                           
        try (Scanner scanner = new Scanner(fail, "UTF-8")) {                                                                                                                                                                               
            while (scanner.hasNextLine()) {                                                                                                                                                                                                
                sõnad.add(scanner.nextLine());                                                                                                                                                                                             
            }                                                                                                                                                                                                                              
                                                                                                                                                                                                                                           
            Random suvaline = new Random();                                                                                                                                                                                                
            String sõna = sõnad.get(suvaline.nextInt(sõnad.size())); // võtame failist suvalise sõna, miinimum indeks on 0 ja max on sõnade listi suurus                                                                                   
                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                           
            // System.out.println(sõna);                                                                                                                                                                                                   
            // Kui ülemiselt realt // ära võtta, näitab see sõna ette. Kasulik programmi testimisel.                                                                                                                                       
                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                           
            List<Character> mängijaarvab = new ArrayList<>();       // List, kuhu jäädvustada mängija ära arvatavaid tähti                                                                                                                 
            SõnaSeis(sõna, mängijaarvab);                           // Kontrollib jooksvalt sõna seisu, kui mitu tähte on ära arvatud.                                                                                                     
                                                                                                                                                                                                                                           
            int valeVastuseLoendur = 0;                             // Vale vastuse loendaja, mille abil hakata kriipsujukut printima.                                                                                                     
                                                                                                                                                                                                                                           
            while (true) {                                                                                                                                                                                                                 
                                                                                                                                                                                                                                           
                SõnaSeis(sõna, mängijaarvab);                                                                                                                                                                                              
                if (!Pakkumine(klaviatuuriInput, sõna, mängijaarvab)) { // Kui pakutav pole õige, siis ...                                                                                                                                 
                    valeVastuseLoendur++;                               // ... siis suurendame vale vastuse loendurit.                                                                                                                     
                }                                                                                                                                                                                                                          
                                                                                                                                                                                                                                           
                if (SõnaSeis(sõna, mängijaarvab)) {                 // Kui SõnaSeis tuleb true väärtusega, ehk sõna on täielikult ära arvatud ...                                                                                          
                    System.out.println("Võitsid!!!");               // ... siis tuleme while-tsüklist välja.                                                                                                                               
                    break;                                                                                                                                                                                                                 
                }                                                                                                                                                                                                                          
                                                                                                                                                                                                                                           
                System.out.println("Proovi ära arvata terve sõna: ");                                                                                                                                                                      
                if (klaviatuuriInput.nextLine().equals(sõna)) {     // Kui mängija pakub terve sõna õigesti, siis tuleme while-tsüklist välja.                                                                                             
                    System.out.println("Võitsid!!!");                                                                                                                                                                                      
                    break;                                                                                                                                                                                                                 
                } else {                                                                                                                                                                                                                   
                    System.out.println("Polnud õige sõna, proovi uuesti: ");  // Kui tervet sõna ära ei arvatud, siis see ei loeta valeks.                                                                                                 
                }                                                                                                                                                                                                                          
                                                                                                                                                                                                                                           
                prindiMees(valeVastuseLoendur);                                                                                                                                                                                            
                if (valeVastuseLoendur >= 4) {                      // Kui valesid vastuseid on olnud 4 või rohkem, siis mäng on kaotatud.                                                                                                 
                    System.out.println("Kaotasid mängu!");                                                                                                                                                                                 
                    break;                                                                                                                                                                                                                 
                }                                                                                                                                                                                                                          
            }                                                                                                                                                                                                                              
        }                                                                                                                                                                                                                                  
    }                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                           
        // Meetodis Pakkumine haldame mängija pakutavaid tähti:                                                                                                                                                                            
        public static boolean Pakkumine(Scanner klaviatuuriInput, String sõna, List<Character> mängijaarvab) {                                                                                                                             
            System.out.print("Sisesta üks täht, mida sõna ära arvamiseks pakkuda: ");                                                                                                                                                      
            String sõnaPakkumine = klaviatuuriInput.nextLine();             // sõnaPakkumine laseb mängijal sisestada mingi väärtuse                                                                                                       
            mängijaarvab.add(sõnaPakkumine.charAt(0));                      // Võtame tähe 0 indeksil (kui pakkumine tuleb kahetäheline või suurem, võetakse vaid esimene täht)                                                            
            return (sõna.contains(sõnaPakkumine));                          // Kui see pakutud täht on sõnas, siis tagastatakse true.                                                                                                      
        }                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                           
        // Meetodis SõnaSeis kontrollime, mis seisus sõna on, mitu tähte on ära arvatud, asendame tähti lünkadesse:                                                                                                                        
        public static boolean SõnaSeis(String sõna, List<Character> mängijaarvab) {                                                                                                                                                        
        int õigeLoendaja = 0;                                                                                                                                                                                                              
            for (int i = 0; i < sõna.length(); i++) {              // Kui mängija on mingi sõna indeksil oleva tähe ära arvanud, siis ...                                                                                                  
                if (mängijaarvab.contains(sõna.charAt(i))) {                                                                                                                                                                               
                    System.out.print(sõna.charAt(i));             // ... siis prindime selle tähe välja, sellel indeksil kus see täht on                                                                                                   
                    õigeLoendaja++;                               // ning liidame loendajale ühe juurde, et mingil hetkel programm                                                                                                         
                                                                  // oma töö ära saaks lõpetada kui kõik tähed on ära arvatud.                                                                                                             
                } else {                                                                                                                                                                                                                   
                    System.out.print("_" + " ");                  // Kui tähepakkumine polnud õige, siis jääb ikka _ alles.                                                                                                                
                }                                                                                                                                                                                                                          
            }                                                                                                                                                                                                                              
            System.out.print(" ");                                // Tühik formaadi jaoks :)                                                                                                                                               
            return (sõna.length() == õigeLoendaja);               // Kui sõna pikkus ja õigete tähtede loendur on sama pikkusega, tagastame true.                                                                                          
    }                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                           
    // Meetodis prindiMees hakkame välja printima "pootud meest":                                                                                                                                                                          
    public static void prindiMees(int valeVastuseLoendur) {                                                                                                                                                                                
        System.out.println("");                                                                                                                                                                                                            
        System.out.println("  -------");                                                                                                                                                                                                   
        System.out.println("  |     |");                        // "Võlli" põhi tuleb automaatselt kaasa.                                                                                                                                  
        if (valeVastuseLoendur >= 1) {                          // Kui on olnud 1 vale pakkumine, tekib pea                                                                                                                                
            System.out.println("  o");                                                                                                                                                                                                     
        }                                                                                                                                                                                                                                  
        if (valeVastuseLoendur >= 2) {                          // Kui on olnud 2 valet pakkumist, tekivad käed                                                                                                                            
            System.out.println("\\" + "   /");                                                                                                                                                                                             
        }                                                                                                                                                                                                                                  
        if (valeVastuseLoendur >= 3) {                          // 3 valet pakkumist, tekib kehaosa                                                                                                                                        
            System.out.println("  |");                                                                                                                                                                                                     
        }                                                                                                                                                                                                                                  
        if (valeVastuseLoendur >= 4) {                         // 4 valet pakkumist, tekivad jalad, mäng on kaotatud.                                                                                                                      
            System.out.println(" /" + " \\");                                                                                                                                                                                              
        }                                                                                                                                                                                                                                  
        System.out.println("");                                                                                                                                                                                                            
    }                                                                                                                                                                                                                                      
}                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                           
